version: '3.9'

services:
  web:
    build: 
      context: ./public
      dockerfile: Dockerfile  # Point to the correct Dockerfile in the public directory
    container_name: excoapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    links:
     - db


  db:
    build: 
      context: ./db
      dockerfile: Dockerfile  # Point to the correct Dockerfile in the db directory
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
