version: '3.9'  # Recommended to use a recent version

services:
  db:
    build:
      context: ./db  # Make sure this path contains the Dockerfile and SQL scripts
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:  # Persistent data storage for MariaDB

web:
  build: ./public
  container_name: excoapp_web
  depends_on:
    db:
      condition: service_healthy
  ports:
    - "80:80"
  volumes:
    - ./public:/var/www/html
    - ./src:/var/www/src
