version: '3.9'

services:
  web:
    build: 
      context: ./public
      dockerfile: Dockerfile  # Point to the correct Dockerfile in the public directory
    container_name: excoapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    depends_on:
     - db


  db:
    build: 
      context: ./db
      dockerfile: Dockerfile  # Point to the correct Dockerfile in the db directory
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
