version: '3.9'

services:
  web:
    build: 
      context: ./public  # Correction pour pointer vers le bon Dockerfile dans le dossier src
    container_name: excoapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src  # Montage du répertoire src dans le conteneur pour accéder à db.php et d'autres fichiers PHP nécessaires
    depends_on:
      db: 
        condition: service_healthy

  db:
    build: 
      context: ./db  # Assurez-vous que cela pointe vers le dossier contenant le Dockerfile et init.sql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
