version: '3.8'

services:
  web:
    build: 
      context: ./src  # Correction pour pointer vers le bon Dockerfile dans le dossier src
    container_name: excoapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src  # Montage du répertoire src dans le conteneur pour accéder à db.php et d'autres fichiers PHP nécessaires
    depends_on:
      - db

  db:
    build: 
      context: ./db  # Assurez-vous que cela pointe vers le dossier contenant le Dockerfile et init.sql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
