version: '3.8'

services:
  db:
    build: ./db
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin123  # Utilisez un mot de passe fort en production
      MYSQL_DATABASE: employee_leaves
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always  # Notez la correction de l'indentation ici

  web:
    build: ./src  # Correction pour pointer vers le bon Dockerfile qui est dans le dossier src et non public
    container_name: excoapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src  # Cela monte le répertoire src dans le conteneur pour accéder à db.php ou à d'autres fichiers PHP nécessaires
    depends_on:
      - db

volumes:
  db_data:
