version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src  
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=utilisateur
      - MYSQL_PASSWORD=mot_de_passe
      - MYSQL_DATABASE=nom_de_votre_base

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nom_de_votre_base
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: mot_de_passe
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
